// AUTO-GENERATED FILE
// Generated by: Len/Scenes/Refresh Menu
using UnityEditor;
using UnityEditor.SceneManagement;

namespace PlatformCore.Editor.Tools.Scenes
{
	public static class PlatformCoreGeneratedScenesMenu
	{
		[MenuItem("Len/Scenes/Persistent", false, 100)]
		private static void Open_Persistent_0()
		{
			if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
			{
				EditorSceneManager.OpenScene("Assets/_Project/Scenes/Persistent.unity");
			}
		}

		[MenuItem("Len/Scenes/SampleScene", false, 101)]
		private static void Open_SampleScene_1()
		{
			if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
			{
				EditorSceneManager.OpenScene("Assets/_Project/Scenes/SampleScene.unity");
			}
		}

	}
}
