// AUTO-GENERATED FILE
// Generated by: Len/Audio/Generate SoundNames
namespace PlatformCore.Services.Audio
{
	public static class SoundNames
	{
		public const string JumpSample = "event:/JumpSample";
	}
}
